const ush = [
  'buckbrush',
  'hobblebush',
  'rabbitbrush',
  'rabbitbush',
  'smokebush',
  'backrush',
  'bottlebrush',
  'buttonbush',
  'spicebush',
  'staggerbush',
  'steeplebush',
  'bitterbrush',
  'broadbrush',
  'highbush',
  'paintbrush',
  'clubrush',
  'qurush',
  'snowbrush',
  'squush',
  'underbrush',
  'waterthrush',
  'zhush',
  'maybush',
  'snowbush',
  'thornbush',
  'toothbrush',
  'bullrush',
  'hagbush',
  'hairbrush',
  'nailbrush',
  'sagebrush',
  'shadbush',
  'kiddush',
  'outblush',
  'overlush',
  'ambush',
  'bulrush',
  'goldrush',
  'saltbush',
  'woodrush',
  'airbrush',
  'ankush',
  'choush',
  'fattoush',
  'outpush',
  'redbush',
  'rosebush',
  'tarbrush',
  'ablush',
  'fatoush',
  'ganoush',
  'outgush',
  'tarbush',
  'uprush',
  'blush',
  'flush',
  'plush',
  'brush',
  'crush',
  'outrush',
  'smush',
  'thrush',
  'bush',
  'inrush',
  'mush',
  'onrush',
  'push',
  'shush',
  'gush',
  'hush',
  'slush',
  'stoush',
  'lush',
  'stush',
  'rush',
  'tush',
]

function capFirst(name) {
  return name.charAt(0).toUpperCase() + name.slice(1)
}

const generateName = () => {
  const name1 = ush[Math.floor(Math.random() * ush.length)]
  const name2 = ush[Math.floor(Math.random() * ush.length)]

  return `${capFirst(name1)}y ${capFirst(name2)}y`
}

export default generateName
